packages:
  - 'apps/*'
  - 'packages/frontend/orders/*'
  - 'packages/frontend/products/*'
  - 'packages/frontend/*'
  - 'packages/shared/*'
  - 'tools/*'
  - 'packages/*'
  - 'packages/backend/*'
  - 'packages/frontend/ratings/*'
